export const PHYSICS = {
  GRAVITY: 0.5,
  BOUNCE: 0.7,
  FRICTION: 0.98,
  MIN_VELOCITY: 0.5,
};

export const GAME_CONFIG = {
  CANVAS_WIDTH: 340,
  CANVAS_HEIGHT: 460,
  PADDING: 10,
  BOX_WIDTH: 320,
  BOX_HEIGHT: 440,
  GAME_OVER_HEIGHT: 100,
  PARTICLE_COUNT: 8,
  PARTICLE_LIFE: 30,
  PARTICLE_SPEED: 10,
  DROP_COOLDOWN_TIME: 400,
};

export enum GameMode {
  ITALIAN_BRAINROT = "italian-brainrot",
  CATS = "cats",
}
