name: Deploy to Production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: ci-production-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  client:
    runs-on: ubuntu-latest

    steps:
      - name: Setup VERSION_NO_V env var
        run: |
          V_VERSION=${{ github.ref_name }}
          VERSION_NO_V=${V_VERSION:1}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        env:
          MODE: production
        run: yarn install

      - name: Build
        run: yarn build

      # - name: Obfuscate
      #   run: yarn obfuscate

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: S3 Sync (all files)
        run: aws s3 sync dist s3://mergerot-production --delete --exclude '*.html'

      - name: S3 Sync (setup cache control for index.html)
        run: |
          aws s3 sync dist s3://mergerot-production --exclude '*' --include '*.html' --metadata-directive REPLACE --cache-control max-age=0

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ES6RPUU7VNVS0
          PATHS: "/*"
